name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8' # Specify the Java version you want to use

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Package application
      run: mvn package

    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: java-app-artifact
        path: target/*.jar  # Adjust this if you have a different packaging type
