name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: <your-github-username>/<your-repo-name>/actions/checkout@main

      - name: Set up JDK 8
        uses: <your-github-username>/<your-repo-name>/actions/setup-java@main
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Update dependency graph
        uses: <your-github-username>/<your-repo-name>/advanced-security/maven-dependency-submission-action@main
