name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Use a versão estável 2

      - name: Set up JDK 8
        uses: actions/setup-java@v2  # Use a versão estável 2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package --fail-at-end -Dmaven.test.failure.ignore=true  # Constrói o arquivo JAR

      - name: Verificar se o JAR foi criado
        run: |
          if [ -f target/ReideOuros-1.0-SNAPSHOT.jar ]; then
            echo "O arquivo JAR foi criado com sucesso."
          else
            echo "O arquivo JAR não foi encontrado."
            exit 1
          fi

      - name: List project structure
        run: |
          echo "Estrutura do projeto:"
          ls -R  # Lista recursivamente todos 