# Este fluxo de trabalho irá construir um projeto Java com Maven e empacotar o arquivo JAR
# Para mais informações, veja: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Atualizado para a versão estável 3

      - name: Set up JDK 8
        uses: actions/setup-java@v3  # Atualizado para a versão estável 3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package  # Constrói o arquivo JAR

      - name: Run tests
        run: mvn test  # Executa os testes

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Garante que este trabalho seja executado após o trabalho de construção
    steps:
      - name: Verificar se o arquivo JAR foi criado
        run: |
          if [ -f target/ReideOuros-1.0-SNAPSHOT.jar ]; then
            echo "O arquivo JAR foi criado com sucesso."
          else
            echo "O arquivo JAR não foi encontrado."
            exit 1
          fi

      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: ReideOuros-jar
          path: target/ReideOuros-1.0-SNAPSHOT.jar  # Especifica o caminho para o arquivo JAR