# This workflow will build a Java project with Maven and package the JAR file
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Run tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download JAR file
        run: |
          echo "The JAR file is located at: target/ReideOuros-1.0-SNAPSHOT.jar"

      - name: Upload JAR file
        uses: actions/upload-artifact@v2
        with:
          name: ReideOuros-jar
          path: target/ReideOuros-1.0-SNAPSHOT.jar
